# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sofia/ros2_iron/src/UC3/model2code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sofia/ros2_iron/src/UC3/model2code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"utilities\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sofia/ros2_iron/src/UC3/model2code/CMakeFiles /home/sofia/ros2_iron/src/UC3/model2code//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sofia/ros2_iron/src/UC3/model2code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named model2code

# Build rule for target.
model2code: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 model2code
.PHONY : model2code

# fast build rule for target.
model2code/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/build
.PHONY : model2code/fast

code/src/ExtractFromElement.o: code/src/ExtractFromElement.cpp.o
.PHONY : code/src/ExtractFromElement.o

# target to build an object file
code/src/ExtractFromElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/ExtractFromElement.cpp.o
.PHONY : code/src/ExtractFromElement.cpp.o

code/src/ExtractFromElement.i: code/src/ExtractFromElement.cpp.i
.PHONY : code/src/ExtractFromElement.i

# target to preprocess a source file
code/src/ExtractFromElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/ExtractFromElement.cpp.i
.PHONY : code/src/ExtractFromElement.cpp.i

code/src/ExtractFromElement.s: code/src/ExtractFromElement.cpp.s
.PHONY : code/src/ExtractFromElement.s

# target to generate assembly for a file
code/src/ExtractFromElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/ExtractFromElement.cpp.s
.PHONY : code/src/ExtractFromElement.cpp.s

code/src/ExtractFromXML.o: code/src/ExtractFromXML.cpp.o
.PHONY : code/src/ExtractFromXML.o

# target to build an object file
code/src/ExtractFromXML.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/ExtractFromXML.cpp.o
.PHONY : code/src/ExtractFromXML.cpp.o

code/src/ExtractFromXML.i: code/src/ExtractFromXML.cpp.i
.PHONY : code/src/ExtractFromXML.i

# target to preprocess a source file
code/src/ExtractFromXML.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/ExtractFromXML.cpp.i
.PHONY : code/src/ExtractFromXML.cpp.i

code/src/ExtractFromXML.s: code/src/ExtractFromXML.cpp.s
.PHONY : code/src/ExtractFromXML.s

# target to generate assembly for a file
code/src/ExtractFromXML.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/ExtractFromXML.cpp.s
.PHONY : code/src/ExtractFromXML.cpp.s

code/src/Generator.o: code/src/Generator.cpp.o
.PHONY : code/src/Generator.o

# target to build an object file
code/src/Generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/Generator.cpp.o
.PHONY : code/src/Generator.cpp.o

code/src/Generator.i: code/src/Generator.cpp.i
.PHONY : code/src/Generator.i

# target to preprocess a source file
code/src/Generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/Generator.cpp.i
.PHONY : code/src/Generator.cpp.i

code/src/Generator.s: code/src/Generator.cpp.s
.PHONY : code/src/Generator.s

# target to generate assembly for a file
code/src/Generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/Generator.cpp.s
.PHONY : code/src/Generator.cpp.s

code/src/main.o: code/src/main.cpp.o
.PHONY : code/src/main.o

# target to build an object file
code/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/main.cpp.o
.PHONY : code/src/main.cpp.o

code/src/main.i: code/src/main.cpp.i
.PHONY : code/src/main.i

# target to preprocess a source file
code/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/main.cpp.i
.PHONY : code/src/main.cpp.i

code/src/main.s: code/src/main.cpp.s
.PHONY : code/src/main.s

# target to generate assembly for a file
code/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/main.cpp.s
.PHONY : code/src/main.cpp.s

code/src/utils.o: code/src/utils.cpp.o
.PHONY : code/src/utils.o

# target to build an object file
code/src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/utils.cpp.o
.PHONY : code/src/utils.cpp.o

code/src/utils.i: code/src/utils.cpp.i
.PHONY : code/src/utils.i

# target to preprocess a source file
code/src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/utils.cpp.i
.PHONY : code/src/utils.cpp.i

code/src/utils.s: code/src/utils.cpp.s
.PHONY : code/src/utils.s

# target to generate assembly for a file
code/src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model2code.dir/build.make CMakeFiles/model2code.dir/code/src/utils.cpp.s
.PHONY : code/src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... model2code"
	@echo "... code/src/ExtractFromElement.o"
	@echo "... code/src/ExtractFromElement.i"
	@echo "... code/src/ExtractFromElement.s"
	@echo "... code/src/ExtractFromXML.o"
	@echo "... code/src/ExtractFromXML.i"
	@echo "... code/src/ExtractFromXML.s"
	@echo "... code/src/Generator.o"
	@echo "... code/src/Generator.i"
	@echo "... code/src/Generator.s"
	@echo "... code/src/main.o"
	@echo "... code/src/main.i"
	@echo "... code/src/main.s"
	@echo "... code/src/utils.o"
	@echo "... code/src/utils.i"
	@echo "... code/src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

