// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at $datetime$ with M2C version $m2cVersion$
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "$className$.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  $className$ stateMachine("$skillName$");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "$className$ successfully closed" << std::endl;
  return ret;
}

